/**
 * High-frequency isnād / matn labels for names and formulas.
 * Keys: normalizeArabicToken output.
 */
export type HadithNameEntry = {
  labelAr: string;
  labelEn: string;
  kind: "narrator" | "companion" | "formula" | "number" | "book";
};

/** Frequency-driven from opening slices of major collections. */
export const HADITH_NAMES: Record<string, HadithNameEntry> = {
  بن: { kind: "formula", labelAr: "ابن (نسب في الإسناد)", labelEn: "ibn (patronymic in isnād)" },
  ابن: { kind: "formula", labelAr: "ابن (نسب في الإسناد)", labelEn: "ibn (patronymic in isnād)" },
  ابو: { kind: "formula", labelAr: "أبو (كنية)", labelEn: "Abū (kunya)" },
  ابي: { kind: "formula", labelAr: "أبي (كنية مجرورة)", labelEn: "Abī (kunya genitive)" },
  يا: { kind: "formula", labelAr: "أداة نداء", labelEn: "Vocative particle" },
  رواه: { kind: "formula", labelAr: "صيغة تخريج («رواه…»)", labelEn: "Attribution formula (rawāhu)" },
  روي: { kind: "formula", labelAr: "صيغة رواية", labelEn: "Narration formula" },
  وروي: { kind: "formula", labelAr: "صيغة رواية معطوفة", labelEn: "Narration formula (wa-)" },
  وحدثنا: { kind: "formula", labelAr: "صيغة تحديث معطوفة (إسناد)", labelEn: "Transmission formula (wa-ḥaddathanā)" },
  وحدثني: { kind: "formula", labelAr: "صيغة تحديث فردية معطوفة", labelEn: "Transmission formula (wa-ḥaddathanī)" },
  صحيح: { kind: "book", labelAr: "وصف للصحة / إشارة لكتاب الصحيح", labelEn: "Ṣaḥīḥ (sound / collection label)" },
  البخاري: { kind: "book", labelAr: "الإمام البخاري / جامعه الصحيح", labelEn: "al-Bukhārī" },
  يعني: { kind: "formula", labelAr: "تفسير الراوي للفظ («يعني»)", labelEn: "Clarifying ‘yaʿnī’" },
  شيئا: { kind: "formula", labelAr: "شيء (نكرة شائعة في المتون)", labelEn: "Something / a thing" },
  ثلاثا: { kind: "number", labelAr: "ثلاث مرات / ثلاثة", labelEn: "Three times / three" },
  خمس: { kind: "number", labelAr: "خمسة / خمس مرات", labelEn: "Five / five times" },
  اصحاب: { kind: "formula", labelAr: "أصحاب (صحابة أو أتباع)", labelEn: "Companions / followers" },
  اصح: { kind: "formula", labelAr: "أصحّ (صيغة تفضيل للصحة)", labelEn: "Most sound (aṣaḥḥ)" },
  عمر: { kind: "companion", labelAr: "عمر بن الخطاب (غالبًا) — صحابي", labelEn: "ʿUmar (often ibn al-Khaṭṭāb)" },
  عثمان: { kind: "companion", labelAr: "عثمان بن عفان (غالبًا) — صحابي", labelEn: "ʿUthmān (often ibn ʿAffān)" },
  عائشه: { kind: "companion", labelAr: "عائشة أم المؤمنين", labelEn: "ʿĀʾisha, Mother of the Believers" },
  هريره: { kind: "companion", labelAr: "أبو هريرة — صحابي مكثر", labelEn: "Abū Hurayra" },
  عباس: { kind: "companion", labelAr: "ابن عباس (غالبًا) — صحابي", labelEn: "Ibn ʿAbbās (often)" },
  جابر: { kind: "companion", labelAr: "جابر بن عبد الله (غالبًا)", labelEn: "Jābir (often ibn ʿAbd Allāh)" },
  انس: { kind: "companion", labelAr: "أنس بن مالك (غالبًا)", labelEn: "Anas (often ibn Mālik)" },
  مسعود: { kind: "companion", labelAr: "ابن مسعود (غالبًا)", labelEn: "Ibn Masʿūd (often)" },
  سعد: { kind: "companion", labelAr: "سعد (صحابي/تابعي بحسب السياق)", labelEn: "Saʿd (context-dependent)" },
  سعيد: { kind: "narrator", labelAr: "سعيد (راوٍ شائع في الأسانيد)", labelEn: "Saʿīd (common narrator name)" },
  عمرو: { kind: "narrator", labelAr: "عمرو (راوٍ/صحابي بحسب السياق)", labelEn: "ʿAmr (context-dependent)" },
  سفيان: { kind: "narrator", labelAr: "سفيان (الثوري أو ابن عيينة غالبًا)", labelEn: "Sufyān (often al-Thawrī / Ibn ʿUyayna)" },
  ابراهيم: { kind: "narrator", labelAr: "إبراهيم (راوٍ شائع)", labelEn: "Ibrāhīm (common narrator)" },
  اسحاق: { kind: "narrator", labelAr: "إسحاق (راوٍ شائع)", labelEn: "Isḥāq (common narrator)" },
  واسحاق: { kind: "narrator", labelAr: "وإسحاق (عطف في الإسناد)", labelEn: "wa-Isḥāq in isnād" },
  اسماعيل: { kind: "narrator", labelAr: "إسماعيل (راوٍ شائع)", labelEn: "Ismāʿīl" },
  عبيد: { kind: "narrator", labelAr: "عبيد / عبيد الله (راوٍ)", labelEn: "ʿUbayd / ʿUbayd Allāh" },
  قتاده: { kind: "narrator", labelAr: "قتادة (راوٍ مشهور)", labelEn: "Qatāda" },
  قتيبه: { kind: "narrator", labelAr: "قتيبة (راوٍ)", labelEn: "Qutayba" },
  خالد: { kind: "narrator", labelAr: "خالد (راوٍ/صحابي بحسب السياق)", labelEn: "Khālid" },
  وكيع: { kind: "narrator", labelAr: "وكيع بن الجراح (غالبًا)", labelEn: "Wakīʿ" },
  صالح: { kind: "narrator", labelAr: "صالح (راوٍ شائع)", labelEn: "Ṣāliḥ" },
  سليمان: { kind: "narrator", labelAr: "سليمان (راوٍ شائع)", labelEn: "Sulaymān" },
  الزهري: { kind: "narrator", labelAr: "الزهري — إمام في الحديث", labelEn: "al-Zuhrī" },
  حماد: { kind: "narrator", labelAr: "حماد (راوٍ شائع)", labelEn: "Ḥammād" },
  الاعمش: { kind: "narrator", labelAr: "الأعمش — راوٍ مشهور", labelEn: "al-Aʿmash" },
  جعفر: { kind: "narrator", labelAr: "جعفر (راوٍ/صحابي بحسب السياق)", labelEn: "Jaʿfar" },
  بشار: { kind: "narrator", labelAr: "بندار / محمد بن بشار (غالبًا في الأسانيد)", labelEn: "Bundār / Ibn Bashshār" },
  حرب: { kind: "narrator", labelAr: "حرب (راوٍ)", labelEn: "Ḥarb" },
  مسدد: { kind: "narrator", labelAr: "مسدد (راوٍ)", labelEn: "Musaddad" },
  عامر: { kind: "narrator", labelAr: "عامر (راوٍ/صحابي بحسب السياق)", labelEn: "ʿĀmir" },
  شيبه: { kind: "narrator", labelAr: "شيبة (راوٍ)", labelEn: "Shayba" },
  هشام: { kind: "narrator", labelAr: "هشام (راوٍ شائع)", labelEn: "Hishām" },
  محمدا: { kind: "narrator", labelAr: "محمدًا (علم منصوب)", labelEn: "Muḥammad (accusative)" },
  محمد: { kind: "narrator", labelAr: "محمد (النبي ﷺ أو راوٍ بحسب السياق)", labelEn: "Muḥammad (Prophet or narrator by context)" },
  عيسي: { kind: "narrator", labelAr: "عيسى (راوٍ شائع في بعض الطرق)", labelEn: "ʿĪsā (common in some chains)" },
  وابو: { kind: "formula", labelAr: "وأبو (عطف كنية في الإسناد)", labelEn: "wa-Abū in isnād" },
  // --- second wave: wuḍūʾ chains + narrators ---
  انبانا: { kind: "formula", labelAr: "صيغة إنباء (إسناد)", labelEn: "Anbaʾanā transmission formula" },
  اخبره: { kind: "formula", labelAr: "أخبرَه (صيغة إخبار)", labelEn: "Akhbarahu (report formula)" },
  عز: { kind: "formula", labelAr: "عزّ (من «عزّ وجلّ»)", labelEn: "ʿAzza (in ʿazza wa-jall)" },
  وجل: { kind: "formula", labelAr: "جلّ (من «عزّ وجلّ»)", labelEn: "Jalla (in ʿazza wa-jall)" },
  تعالي: { kind: "formula", labelAr: "تعالى (ثناء على الله)", labelEn: "Taʿālā (divine exaltation)" },
  السلام: { kind: "formula", labelAr: "السلام (تحية / اسم الله بحسب السياق)", labelEn: "al-Salām (greeting / Name by context)" },
  بنت: { kind: "formula", labelAr: "بنت (نسب أنثوي)", labelEn: "Bint (daughter of)" },
  ثلاث: { kind: "number", labelAr: "ثلاثة / ثلاث مرات", labelEn: "Three / three times" },
  ثلاثه: { kind: "number", labelAr: "ثلاثة", labelEn: "Three" },
  مرات: { kind: "number", labelAr: "مرات (تكرار)", labelEn: "Times / repetitions" },
  عروه: { kind: "narrator", labelAr: "عروة (بن الزبير غالبًا)", labelEn: "ʿUrwa (often ibn al-Zubayr)" },
  المغيره: { kind: "narrator", labelAr: "المغيرة (بن شعبة غالبًا)", labelEn: "al-Mughīra (often ibn Shuʿba)" },
  نافع: { kind: "narrator", labelAr: "نافع (مولى ابن عمر غالبًا)", labelEn: "Nāfiʿ" },
  معاويه: { kind: "companion", labelAr: "معاوية (بن أبي سفيان غالبًا)", labelEn: "Muʿāwiya" },
  منصور: { kind: "narrator", labelAr: "منصور (راوٍ شائع)", labelEn: "Manṣūr" },
  جرير: { kind: "narrator", labelAr: "جرير (راوٍ شائع)", labelEn: "Jarīr" },
  الوليد: { kind: "narrator", labelAr: "الوليد (راوٍ شائع)", labelEn: "al-Walīd" },
  طلحه: { kind: "companion", labelAr: "طلحة (صحابي/راوٍ بحسب السياق)", labelEn: "Ṭalḥa" },
  الحارث: { kind: "narrator", labelAr: "الحارث (راوٍ شائع)", labelEn: "al-Ḥārith" },
  الزبير: { kind: "companion", labelAr: "الزبير (بن العوام غالبًا)", labelEn: "al-Zubayr" },
  كعب: { kind: "narrator", labelAr: "كعب (راوٍ/صحابي بحسب السياق)", labelEn: "Kaʿb" },
  قيس: { kind: "narrator", labelAr: "قيس (راوٍ شائع)", labelEn: "Qays" },
  القاسم: { kind: "narrator", labelAr: "القاسم (راوٍ شائع)", labelEn: "al-Qāsim" },
  هناد: { kind: "narrator", labelAr: "هناد (راوٍ)", labelEn: "Hannād" },
  عفان: { kind: "narrator", labelAr: "عفان (راوٍ / أو نسبة لعثمان)", labelEn: "ʿAffān" },
  المسيب: { kind: "narrator", labelAr: "المسيب (سعيد بن المسيب غالبًا في السلسلة)", labelEn: "al-Musayyab" },
  ادم: { kind: "narrator", labelAr: "آدم (راوٍ شائع في بعض الطرق)", labelEn: "Ādam (narrator)" },
  يسار: { kind: "narrator", labelAr: "يسار (راوٍ)", labelEn: "Yasār" },
  زهير: { kind: "narrator", labelAr: "زهير (راوٍ شائع)", labelEn: "Zuhayr" },
  العلاء: { kind: "narrator", labelAr: "العلاء (راوٍ)", labelEn: "al-ʿAlāʾ" },
  ربيعه: { kind: "narrator", labelAr: "ربيعة (راوٍ شائع)", labelEn: "Rabīʿa" },
  اسامه: { kind: "companion", labelAr: "أسامة (بن زيد غالبًا)", labelEn: "Usāma" },
  علقمه: { kind: "narrator", labelAr: "علقمة (راوٍ)", labelEn: "ʿAlqama" },
  حبيب: { kind: "narrator", labelAr: "حبيب (راوٍ)", labelEn: "Ḥabīb" },
  رافع: { kind: "narrator", labelAr: "رافع (راوٍ/صحابي)", labelEn: "Rāfiʿ" },
  زياد: { kind: "narrator", labelAr: "زياد (راوٍ)", labelEn: "Ziyād" },
  نمير: { kind: "narrator", labelAr: "نمير (راوٍ)", labelEn: "Numayr" },
  عمار: { kind: "companion", labelAr: "عمار (بن ياسر غالبًا)", labelEn: "ʿAmmār" },
  الثوري: { kind: "narrator", labelAr: "الثوري — سفيان", labelEn: "al-Thawrī" },
  جبريل: { kind: "narrator", labelAr: "جبريل عليه السلام (في حديث جبريل وغيره)", labelEn: "Jibrīl (Gabriel)" },
  عون: { kind: "narrator", labelAr: "عون (راوٍ)", labelEn: "ʿAwn" },
  مجاهد: { kind: "narrator", labelAr: "مجاهد (المفسر/الراوي)", labelEn: "Mujāhid" },
  عيينه: { kind: "narrator", labelAr: "عيينة (ابن عيينة غالبًا في السلسلة)", labelEn: "ʿUyayna" },
  الليث: { kind: "narrator", labelAr: "الليث (بن سعد غالبًا)", labelEn: "al-Layth" },
  عقيل: { kind: "narrator", labelAr: "عقيل (راوٍ)", labelEn: "ʿUqayl" },
  الزناد: { kind: "narrator", labelAr: "الزناد (راوٍ في بعض الطرق)", labelEn: "al-Zinād" },
  سهيل: { kind: "narrator", labelAr: "سهيل (راوٍ)", labelEn: "Suhayl" },
  همام: { kind: "narrator", labelAr: "همام (راوٍ)", labelEn: "Hammām" },
  وائل: { kind: "narrator", labelAr: "وائل (راوٍ)", labelEn: "Wāʾil" },
  اسرائيل: { kind: "narrator", labelAr: "إسرائيل (راوٍ)", labelEn: "Isrāʾīl" },
  جريج: { kind: "narrator", labelAr: "جريج / ابن جريج (غالبًا)", labelEn: "Jurayj / Ibn Jurayj" },
  عكرمه: { kind: "narrator", labelAr: "عكرمة (راوٍ مشهور)", labelEn: "ʿIkrima" },
  دينار: { kind: "narrator", labelAr: "دينار (في أسماء مثل أبي صالح)", labelEn: "Dīnār (in names)" },
  الخدري: { kind: "companion", labelAr: "أبو سعيد الخدري", labelEn: "Abū Saʿīd al-Khudrī" },
  الاوزاعي: { kind: "narrator", labelAr: "الأوزاعي — إمام", labelEn: "al-Awzāʿī" },
  هاشم: { kind: "narrator", labelAr: "هاشم (راوٍ/نسب)", labelEn: "Hāshim" },
  النضر: { kind: "narrator", labelAr: "النضر (راوٍ)", labelEn: "al-Naḍr" },
  ليلي: { kind: "narrator", labelAr: "ليلى (راوية/نسب)", labelEn: "Laylā" },
  التيمي: { kind: "narrator", labelAr: "التيمي (نسبة)", labelEn: "al-Taymī" },
  اليمان: { kind: "narrator", labelAr: "اليمان (نسب كأبي حذيفة)", labelEn: "al-Yamān" },
  عوف: { kind: "narrator", labelAr: "عوف (راوٍ)", labelEn: "ʿAwf" },
  شريح: { kind: "narrator", labelAr: "شريح (راوٍ/قاضٍ)", labelEn: "Shurayḥ" },
  هلال: { kind: "narrator", labelAr: "هلال (راوٍ)", labelEn: "Hilāl" },
  عتبه: { kind: "narrator", labelAr: "عتبة (راوٍ)", labelEn: "ʿUtba" },
  بلال: { kind: "companion", labelAr: "بلال (بن رباح غالبًا)", labelEn: "Bilāl" },
  طالب: { kind: "narrator", labelAr: "طالب (في أسماء مثل أبي طالب)", labelEn: "Ṭālib (in names)" },
  الشافعي: { kind: "narrator", labelAr: "الشافعي — إمام المذهب", labelEn: "al-Shāfiʿī" },
  والشافعي: { kind: "narrator", labelAr: "والشافعي (عطف تخريج)", labelEn: "wa-al-Shāfiʿī" },
  صاحب: { kind: "formula", labelAr: "صاحب (صحبة/وصف)", labelEn: "Companion / ṣāḥib" },
  سالت: { kind: "formula", labelAr: "سألتُ (صيغة سؤال الصحابي)", labelEn: "I asked (companion question formula)" },
  نحوه: { kind: "formula", labelAr: "نحوه (إشارة لمعنى مقارب في التخريج)", labelEn: "Naḥwahu (similar wording note)" },
  نحو: { kind: "formula", labelAr: "نحو (تقريب المعنى)", labelEn: "Naḥw (approximately)" },
  قط: { kind: "formula", labelAr: "قطّ (ظرف لاستغراق الماضي)", labelEn: "Qaṭṭ (ever / at all)" },
  حدث: { kind: "formula", labelAr: "حدّث (جذر التحديث)", labelEn: "Ḥaddatha root form" },
  امتي: { kind: "formula", labelAr: "أمتي (خطاب نبوي للأمة)", labelEn: "My ummah" },
};
