/**
 * High-frequency hadith matn lemmas that often miss Quran surface match.
 * Keys: normalizeArabicToken output (أإآٱ→ا, ة→ه, ى→ي, no tashkeel).
 */
export type HadithCoreGloss = {
  root?: string;
  lemma?: string;
  pos?: string[];
  senseAr: string;
  senseEn: string;
  /** Optional short rhetoric note (hadith formula / style), Arabic. */
  rhetoricAr?: string;
  rhetoricEn?: string;
};

export const HADITH_CORE_GLOSS: Record<string, HadithCoreGloss> = {
  اعمال: {
    root: "عمل",
    lemma: "أعمال",
    pos: ["N"],
    senseAr: "جمع عمل: الأفعال والتصرفات التي يحاسب عليها العبد.",
    senseEn: "Deeds / actions (plural of ʿamal).",
  },
  عمل: {
    root: "عمل",
    lemma: "عمل",
    pos: ["N"],
    senseAr: "الفعل الصادر عن المكلّف؛ في الحديث يُقرن كثيرًا بالنية.",
    senseEn: "Deed / act (often paired with intention).",
  },
  نيه: {
    root: "نوي",
    lemma: "نية",
    pos: ["N"],
    senseAr: "القصد والعزم في القلب على الفعل؛ مدار صحة كثير من الأعمال.",
    senseEn: "Intention; inward resolve behind an act.",
  },
  نيات: {
    root: "نوي",
    lemma: "نيات",
    pos: ["N"],
    senseAr: "جمع نية: المقصودات الباطنة التي تُميّز الأعمال.",
    senseEn: "Intentions (plural of niyya).",
  },
  نوي: {
    root: "نوي",
    lemma: "نوى",
    pos: ["V"],
    senseAr: "قصد وعزم؛ «ما نوى» أي ما قصده في باطنه.",
    senseEn: "Intended / resolved.",
  },
  هجره: {
    root: "هجر",
    lemma: "هجرة",
    pos: ["N"],
    senseAr: "الانتقال وترك الوطن؛ وفي الشرع هجرة إلى الله ورسوله.",
    senseEn: "Migration / hijra.",
  },
  هجرت: {
    root: "هجر",
    lemma: "هجرة",
    pos: ["N"],
    senseAr: "الانتقال وترك الوطن؛ وفي الشرع هجرة إلى الله ورسوله.",
    senseEn: "Migration / hijra.",
  },
  دنيا: {
    root: "دنو",
    lemma: "دنيا",
    pos: ["N"],
    senseAr: "الحياة الحاضرة وما فيها من متاع زائل مقابل الآخرة.",
    senseEn: "This world / worldly life.",
  },
  يصيب: {
    root: "صوب",
    lemma: "أصاب",
    pos: ["V"],
    senseAr: "ينال ويبلغ؛ «لدنيا يصيبها» أي يطلب متاعًا يناله.",
    senseEn: "To obtain / afflict / reach.",
  },
  امرئ: {
    root: "مرأ",
    lemma: "امرئ",
    pos: ["N"],
    senseAr: "الإنسان / الشخص.",
    senseEn: "Person / man.",
  },
  امراه: {
    root: "مرأ",
    lemma: "امرأة",
    pos: ["N"],
    senseAr: "أنثى من البشر.",
    senseEn: "Woman.",
  },
  حلال: {
    root: "حلل",
    lemma: "حلال",
    pos: ["N"],
    senseAr: "المباح شرعًا؛ ضد الحرام.",
    senseEn: "Lawful / permitted.",
  },
  حرام: {
    root: "حرم",
    lemma: "حرام",
    pos: ["N"],
    senseAr: "الممنوع شرعًا؛ ضد الحلال.",
    senseEn: "Unlawful / forbidden.",
  },
  مشتبهات: {
    root: "شبه",
    lemma: "مشتبهات",
    pos: ["N"],
    senseAr: "أمور يلتبس حكمها بين الحلال والحرام.",
    senseEn: "Doubtful / ambiguous matters.",
  },
  شبهات: {
    root: "شبه",
    lemma: "شبهات",
    pos: ["N"],
    senseAr: "مواضع الاشتباه في الحكم الشرعي.",
    senseEn: "Doubts / dubious matters.",
  },
  اتقى: {
    root: "وقي",
    lemma: "اتقى",
    pos: ["V"],
    senseAr: "توقّى واجتنب؛ طلب السلامة بالاحتراز.",
    senseEn: "Guarded against / avoided.",
  },
  استبرا: {
    root: "برا",
    lemma: "استبرأ",
    pos: ["V"],
    senseAr: "طلب البراءة والسلامة لدينه وعرضه.",
    senseEn: "Sought to keep clear / protect (faith and honor).",
  },
  دين: {
    root: "دين",
    lemma: "دين",
    pos: ["N"],
    senseAr: "الدين والملة؛ ما يتعبّد به العبد.",
    senseEn: "Religion / faith.",
  },
  عرضه: {
    root: "عرض",
    lemma: "عرض",
    pos: ["N"],
    senseAr: "العِرض: الشرف والمروءة التي يُصان بها الإنسان.",
    senseEn: "Honor / reputation.",
  },
  عرض: {
    root: "عرض",
    lemma: "عرض",
    pos: ["N"],
    senseAr: "الشرف والمروءة.",
    senseEn: "Honor / reputation.",
  },
  راعي: {
    root: "رعي",
    lemma: "راعٍ",
    pos: ["N"],
    senseAr: "من يرعى الغنم أو القوم؛ في المثل: من يقترب من الحمى.",
    senseEn: "Shepherd / caretaker.",
  },
  يرعي: {
    root: "رعي",
    lemma: "يرعى",
    pos: ["V"],
    senseAr: "يرعى الماشية أو يحوطها.",
    senseEn: "Grazes / tends.",
  },
  حمي: {
    root: "حمي",
    lemma: "حمى",
    pos: ["N"],
    senseAr: "الحِمى: المرعى المحظور؛ يُضرب مثلاً لمحارم الله.",
    senseEn: "Sanctuary / protected pasture (metaphor for Allah’s prohibitions).",
  },
  محارم: {
    root: "حرم",
    lemma: "محارم",
    pos: ["N"],
    senseAr: "ما حرّمه الله؛ حدود لا تُنتهك.",
    senseEn: "Prohibitions / sacred bounds.",
  },
  جسد: {
    root: "جسد",
    lemma: "جسد",
    pos: ["N"],
    senseAr: "البدن.",
    senseEn: "Body.",
  },
  مضغه: {
    root: "مضغ",
    lemma: "مضغة",
    pos: ["N"],
    senseAr: "قطعة لحم صغيرة؛ في الحديث تُطلق على القلب.",
    senseEn: "Morsel of flesh (here: the heart).",
  },
  صلح: {
    root: "صلح",
    lemma: "صلح",
    pos: ["V"],
    senseAr: "صلح الأمر: استقام وزال فساده.",
    senseEn: "Became sound / reformed.",
  },
  صلحت: {
    root: "صلح",
    lemma: "صلحت",
    pos: ["V"],
    senseAr: "استقامت وصلحت.",
    senseEn: "Became sound (feminine).",
  },
  فسد: {
    root: "فسد",
    lemma: "فسد",
    pos: ["V"],
    senseAr: "فسد الشيء: بطل صلاحه.",
    senseEn: "Became corrupt / spoiled.",
  },
  فسدت: {
    root: "فسد",
    lemma: "فسدت",
    pos: ["V"],
    senseAr: "فسدَت واستحالت عن الصلاح.",
    senseEn: "Became corrupt (feminine).",
  },
  قلب: {
    root: "قلب",
    lemma: "قلب",
    pos: ["N"],
    senseAr: "العضو والمقصود المعنوي: محل الإيمان والنوايا.",
    senseEn: "Heart (physical and spiritual seat of faith).",
  },
  اسلام: {
    root: "سلم",
    lemma: "إسلام",
    pos: ["N"],
    senseAr: "الانقياد الظاهر لأوامر الله بالشهادتين والأركان.",
    senseEn: "Islam — outward submission to Allah.",
  },
  ايمان: {
    root: "امن",
    lemma: "إيمان",
    pos: ["N"],
    senseAr: "التصديق الجازم بالله وملائكته وكتبه ورسله واليوم الآخر والقدر.",
    senseEn: "Faith / īmān.",
  },
  احسان: {
    root: "حسن",
    lemma: "إحسان",
    pos: ["N"],
    senseAr: "أن تعبد الله كأنك تراه؛ أعلى مراتب الدين في حديث جبريل.",
    senseEn: "Iḥsān — worshipping Allah as though you see Him.",
  },
  صلاه: {
    root: "صلو",
    lemma: "صلاة",
    pos: ["N"],
    senseAr: "الركن الثاني؛ العبادة المفروضة خمسًا.",
    senseEn: "Prayer / ṣalāh.",
  },
  زكاه: {
    root: "زكو",
    lemma: "زكاة",
    pos: ["N"],
    senseAr: "حق معلوم في المال يُخرج للفقراء.",
    senseEn: "Zakāh / almsgiving.",
  },
  صوم: {
    root: "صوم",
    lemma: "صوم",
    pos: ["N"],
    senseAr: "الإمساك عن المفطرات من الفجر إلى المغرب.",
    senseEn: "Fasting.",
  },
  حج: {
    root: "حجج",
    lemma: "حج",
    pos: ["N"],
    senseAr: "قصد البيت الحرام لأداء المناسك لمن استطاع.",
    senseEn: "Hajj / pilgrimage.",
  },
  مسلم: {
    root: "سلم",
    lemma: "مسلم",
    pos: ["N"],
    senseAr: "من دخل في الإسلام؛ من سلم المسلمون من لسانه ويده.",
    senseEn: "Muslim.",
  },
  مؤمن: {
    root: "امن",
    lemma: "مؤمن",
    pos: ["N"],
    senseAr: "من اتصف بالإيمان الباطن والظاهر.",
    senseEn: "Believer / muʾmin.",
  },
  مومن: {
    root: "امن",
    lemma: "مؤمن",
    pos: ["N"],
    senseAr: "من اتصف بالإيمان الباطن والظاهر.",
    senseEn: "Believer / muʾmin.",
  },
  جنه: {
    root: "جنن",
    lemma: "جنة",
    pos: ["N"],
    senseAr: "دار النعيم في الآخرة.",
    senseEn: "Paradise / garden.",
  },
  نار: {
    root: "نور",
    lemma: "نار",
    pos: ["N"],
    senseAr: "نار جهنم؛ دار العقاب.",
    senseEn: "Hellfire.",
  },
  توبه: {
    root: "توب",
    lemma: "توبة",
    pos: ["N"],
    senseAr: "الرجوع عن الذنب إلى الله بالندم والإقلاع والعزم.",
    senseEn: "Repentance.",
  },
  ذنب: {
    root: "ذنب",
    lemma: "ذنب",
    pos: ["N"],
    senseAr: "المعصية وما يُؤاخذ به العبد.",
    senseEn: "Sin.",
  },
  رزق: {
    root: "رزق",
    lemma: "رزق",
    pos: ["N"],
    senseAr: "ما ينفع العبد من عطاء الله.",
    senseEn: "Provision / sustenance.",
  },
  علم: {
    root: "علم",
    lemma: "علم",
    pos: ["N"],
    senseAr: "المعرفة الشرعية وغيرها مما يُطلب لله.",
    senseEn: "Knowledge.",
  },
  صبر: {
    root: "صبر",
    lemma: "صبر",
    pos: ["N"],
    senseAr: "حبس النفس على طاعة الله وعن معصيته وعند المصيبة.",
    senseEn: "Patience / steadfastness.",
  },
  بر: {
    root: "برر",
    lemma: "برّ",
    pos: ["N"],
    senseAr: "الإحسان والطاعة؛ ومنه برّ الوالدين.",
    senseEn: "Righteousness / kindness (incl. to parents).",
  },
  جهاد: {
    root: "جهد",
    lemma: "جهاد",
    pos: ["N"],
    senseAr: "بذل الوسع في سبيل الله؛ له مراتب متعددة في النصوص.",
    senseEn: "Striving / jihād in the path of Allah.",
  },
  يكح: {
    root: "نكح",
    lemma: "ينكح",
    pos: ["V"],
    senseAr: "يتزوّج.",
    senseEn: "Marries.",
  },
  ينكح: {
    root: "نكح",
    lemma: "ينكح",
    pos: ["V"],
    senseAr: "يتزوّج.",
    senseEn: "Marries.",
  },
  هاجر: {
    root: "هجر",
    lemma: "هاجر",
    pos: ["V"],
    senseAr: "ترك وطنه مهاجرًا؛ ومنه الهجرة النبوية.",
    senseEn: "Migrated / emigrated.",
  },
  ملك: {
    root: "ملك",
    lemma: "ملك",
    pos: ["N"],
    senseAr: "صاحب السلطان؛ في المثل: لكل ملك حمى.",
    senseEn: "King / sovereign.",
  },
  امور: {
    root: "امر",
    lemma: "أمور",
    pos: ["N"],
    senseAr: "جمع أمر: الشؤون والقضايا.",
    senseEn: "Matters / affairs.",
  },
  كثير: {
    root: "كثر",
    lemma: "كثير",
    pos: ["ADJ"],
    senseAr: "ضد القليل؛ عدد وافر.",
    senseEn: "Many / much.",
  },
  يعلم: {
    root: "علم",
    lemma: "يعلم",
    pos: ["V"],
    senseAr: "يدري ويعرف.",
    senseEn: "Knows.",
  },
  وقع: {
    root: "وقع",
    lemma: "وقع",
    pos: ["V"],
    senseAr: "سقط أو حصل فيه؛ «وقع في الشبهات».",
    senseEn: "Fell into / occurred.",
  },
  يوشك: {
    root: "وشك",
    lemma: "يوشك",
    pos: ["V"],
    senseAr: "يقارب ويُسرع أن يقع.",
    senseEn: "Is about to / nearly.",
  },
  بين: {
    root: "بين",
    lemma: "بيّن",
    pos: ["ADJ"],
    senseAr: "واضح ظاهر؛ «الحلال بيّن».",
    senseEn: "Clear / evident.",
  },
};
