import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { parseApiKeys } from "@/lib/api-keys";

export const MPT_RUNTIME_STOCK_KEYS_FILE = join(
  process.cwd(),
  "services/money-printer-turbo/.runtime-stock-keys.env",
);

function envLine(name: string, value: string): string {
  return `${name}=${value.replace(/\r?\n/g, "").trim()}\n`;
}

/** Copy Next.js stock-footage keys so the Python engine can fetch Pexels clips. */
export function syncMptStockKeysFromEnv(
  env: NodeJS.ProcessEnv = process.env,
  filePath = MPT_RUNTIME_STOCK_KEYS_FILE,
): { pexels: number; pixabay: number } {
  const pexels = parseApiKeys(env.PEXELS_API_KEY, env.PEXELS_API_KEYS);
  const pixabay = parseApiKeys(env.PIXABAY_API_KEY, env.PIXABAY_API_KEYS);
  if (!pexels.length && !pixabay.length) {
    return { pexels: 0, pixabay: 0 };
  }
  const lines = [
    "# Generated by arabya-web — do not commit. Mode 0600.",
    pexels.length ? envLine("PEXELS_API_KEY", pexels.join(",")) : "",
    pixabay.length ? envLine("PIXABAY_API_KEY", pixabay.join(",")) : "",
  ]
    .filter(Boolean)
    .join("");
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, lines, { encoding: "utf8", mode: 0o600 });
  return { pexels: pexels.length, pixabay: pixabay.length };
}

/** Block a Pexels/Pixabay job before MPT stalls at 5% with an empty key list. */
export function stockKeyErrorForSource(
  source: string,
  counts: { pexels: number; pixabay: number },
): "missing_pexels_key" | "missing_pixabay_key" | null {
  if (source === "pexels" && counts.pexels === 0) return "missing_pexels_key";
  if (source === "pixabay" && counts.pixabay === 0) return "missing_pixabay_key";
  return null;
}
