import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { parseApiKeys } from "@/lib/api-keys";

export const MPT_RUNTIME_STOCK_KEYS_FILE = join(
  process.cwd(),
  "services/money-printer-turbo/.runtime-stock-keys.env",
);

const PEXELS_ENV_NAMES = [
  "PEXELS_API_KEY",
  "PEXELS_API_KEYS",
  "MPT_PEXELS_API_KEY",
  "MPT_PEXELS_API_KEYS",
] as const;

const PIXABAY_ENV_NAMES = [
  "PIXABAY_API_KEY",
  "PIXABAY_API_KEYS",
  "MPT_PIXABAY_API_KEY",
  "MPT_PIXABAY_API_KEYS",
] as const;

export function defaultStockEnvFiles(cwd = process.cwd()): string[] {
  return [
    join(cwd, "services/money-printer-turbo/.runtime-stock-keys.env"),
    join(cwd, ".env.production.local"),
    join(cwd, ".env.production"),
    join(cwd, ".env.local"),
    join(cwd, ".env"),
    join(cwd, "services/money-printer-turbo/.env"),
  ];
}

export function parseDotenvText(text: string): Record<string, string> {
  const values: Record<string, string> = {};
  for (const raw of text.split(/\r?\n/)) {
    let line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("export ")) line = line.slice(7).trim();
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const name = line.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) continue;
    let value = line.slice(eq + 1).trim();
    if (
      value.length >= 2 &&
      value[0] === value[value.length - 1] &&
      (value[0] === '"' || value[0] === "'")
    ) {
      value = value.slice(1, -1);
    }
    if (!(name in values)) values[name] = value;
  }
  return values;
}

export function mergeDotenvFiles(paths: string[]): Record<string, string> {
  const values: Record<string, string> = {};
  for (const filePath of paths) {
    let text = "";
    try {
      text = readFileSync(filePath, "utf8");
    } catch {
      continue;
    }
    for (const [name, value] of Object.entries(parseDotenvText(text))) {
      if (!(name in values)) values[name] = value;
    }
  }
  return values;
}

function keysFromRecord(
  record: Record<string, string | undefined>,
  names: readonly string[],
): string[] {
  return parseApiKeys(...names.map((name) => record[name]));
}

function envLine(name: string, value: string): string {
  return `${name}=${value.replace(/\r?\n/g, "").trim()}\n`;
}

/** Copy Next.js / dotenv stock-footage keys so the Python engine can fetch Pexels clips. */
export function syncMptStockKeysFromEnv(
  env: NodeJS.ProcessEnv = process.env,
  filePath = MPT_RUNTIME_STOCK_KEYS_FILE,
  dotenvPaths: string[] | null = null,
): { pexels: number; pixabay: number } {
  const fileValues = mergeDotenvFiles(dotenvPaths ?? defaultStockEnvFiles());
  const pexels =
    keysFromRecord(env, PEXELS_ENV_NAMES).length > 0
      ? keysFromRecord(env, PEXELS_ENV_NAMES)
      : keysFromRecord(fileValues, PEXELS_ENV_NAMES);
  const pixabay =
    keysFromRecord(env, PIXABAY_ENV_NAMES).length > 0
      ? keysFromRecord(env, PIXABAY_ENV_NAMES)
      : keysFromRecord(fileValues, PIXABAY_ENV_NAMES);
  if (!pexels.length && !pixabay.length) {
    return { pexels: 0, pixabay: 0 };
  }
  const lines = [
    "# Generated by arabya-web — do not commit. Mode 0600.",
    pexels.length ? envLine("PEXELS_API_KEY", pexels.join(",")) : "",
    pixabay.length ? envLine("PIXABAY_API_KEY", pixabay.join(",")) : "",
  ]
    .filter(Boolean)
    .join("");
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, lines, { encoding: "utf8", mode: 0o600 });
  return { pexels: pexels.length, pixabay: pixabay.length };
}

/** Block a Pexels/Pixabay job before MPT stalls at 5% with an empty key list. */
export function stockKeyErrorForSource(
  source: string,
  counts: { pexels: number; pixabay: number },
): "missing_pexels_key" | "missing_pixabay_key" | null {
  if (source === "pexels" && counts.pexels === 0) return "missing_pexels_key";
  if (source === "pixabay" && counts.pixabay === 0) return "missing_pixabay_key";
  return null;
}
